### PR TITLE
feat(net): add "helm.sh/..." annotation on lb deployment

### PR DESCRIPTION
**Pull request by hanxueluo**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @hicaistar @whalecold 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
LGTM
@hicaistar

**Comment by hanxueluo** [comment]
this PR is for https://github.com/caicloud/prod-issue/issues/931

**Pull request merged**
